### ISSUE TITLE
Getting an error while using this plugin

### ISSUE THREAD

**Issue by IgnusG** [dominique-mueller/simple-progress-webpack-plugin#10] opened 2017-05-03 18:01 UTC
I'm getting this error every time I use this plugin:
```
/home/user/project/node_modules/webpack-dev-server/bin/webpack-dev-server.js:365
		throw e;
		^

TypeError: Cannot read property 'replace' of undefined
    at MinimalLogger.ProgressPlugin (/home/user/project/node_modules/simple-progress-webpack-plugin/logger/minimal-logger.js:74:6)
    at update (/home/user/project/node_modules/webpack/lib/ProgressPlugin.js:41:5)
    at Compilation.<anonymous> (/home/user/project/node_modules/webpack/lib/ProgressPlugin.js:71:6)
    at Compilation.applyPlugins1 (/home/user/project/node_modules/tapable/lib/Tapable.js:75:14)
    at Compilation.buildModule (/home/user/project/node_modules/webpack/lib/Compilation.js:134:8)
    at moduleFactory.create (/home/user/project/node_modules/webpack/lib/Compilation.js:429:9)
    at MultiModuleFactory.create (/home/user/project/node_modules/webpack/lib/MultiModuleFactory.js:17:3)
    at Compilation._addModuleChain (/home/user/project/node_modules/webpack/lib/Compilation.js:378:17)
    at Compilation.addEntry (/home/user/project/node_modules/webpack/lib/Compilation.js:460:8)
    at Compiler.compiler.plugin (/home/user/project/node_modules/webpack/lib/MultiEntryPlugin.js:28:16)
    at Compiler.applyPluginsParallel (/home/user/project/node_modules/tapable/lib/Tapable.js:229:14)
    at /home/user/project/node_modules/webpack/lib/Compiler.js:483:8
    at Compiler.applyPluginsAsyncSeries (/home/user/project/node_modules/tapable/lib/Tapable.js:131:46)
    at Compiler.compile (/home/user/project/node_modules/webpack/lib/Compiler.js:476:7)
    at /home/user/project/node_modules/webpack/lib/Compiler.js:46:17
    at next (/home/user/project/node_modules/tapable/lib/Tapable.js:138:11)

npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
```
webpack: 2.4.1
webpack-dev-server: 2.4.5

**Comment by dominique-mueller** [comment] 2017-05-03 19:18
Duplicate of #7 - fixed with v1.0.3 released a few moments ago. Let me know when you have other issues!

**Closed by dominique-mueller** 2017-05-03 19:18 UTC
